Tagging on grasp
cms-PdmV/GrASP pull request #93
Opened 2021-11-23 09:14 UTC by hessikaveh

Adding the tagging feature,
Opening a pull request on the first working version, to fix styling and other issues.
Issues:
*The undo and redo is not implemented 
*scroll behavior on the Tags column of the table 

![ezgif-2-24ad8b319c35](https://user-images.githubusercontent.com/13552751/142997694-c7da3fdb-6cce-47ec-b398-00b7ca556024.gif)
can be tested here:
https://pdmv-dev-proxy.web.cern.ch/samples/existing?name=RunIISummer20UL17*GEN&pwg=JME

2021-11-23 10:39 UTC, justinasr requested changes
There is another issue, not with this PR, but with GrASP itself. Whenever stuff is tagged, users probably immediately expect it to appear in the "User tagged samples" tables. Unfortunately we have two separate tables in DB for "existing" and "user tagged" samples, maybe it would be possible to somehow merge them and have only one.

2021-11-23 10:39 UTC, justinasr commented on update_scripts/update_existing_samples.py
> +            other_tags = sorted_join(request['tags'])
This is completely missing the bidirectionality of GrASP and McM updates. `other_tags = sorted_json(request['tags'])` will always overwrite any changes in GrASP with tags in McM. Check the `process_interested_pwgs_update` method.

2021-11-23 10:39 UTC, justinasr commented on update_scripts/update_existing_samples.py
> +
Redundant empty line.

2021-11-23 10:39 UTC, justinasr commented on frontend/src/router/index.js
> +import axios from 'axios'
I don't see why any of the changes in this file are needed?

2021-11-23 10:39 UTC, justinasr commented on frontend/src/components/ExistingSamples.vue
> +    <footer v-if="selectAllChecked || selectAllIndeterminate">
Why are there two footers in the page? The second one completely covers the first one and "Add PWG" and "Remove PWG" buttons are no longer there.

2021-11-23 10:39 UTC, justinasr commented on api/existing_samples_api.py
> +                other_tags = clean_split(entry['tags'])
These tags are _other_ given what reference, i.e. what are _the main_ tags then?

2021-11-23 10:39 UTC, justinasr commented on frontend/src/components/ExistingSamples.vue
> +      <b>GrASP Custom Tag in samples</b>
I'm not sure about "GrASP Custom Tag", why not just "tag"?

2021-11-23 10:39 UTC, justinasr commented on frontend/src/components/ExistingSamples.vue
> +          {{entry.tags}}
Would it be possible to add the "Add tag" and "Remove tag" buttons like in interested PWGs cell?

2021-11-23 17:18 UTC, hessikaveh commented
> There is another issue, not with this PR, but with GrASP itself. Whenever stuff is tagged, users probably immediately expect it to appear in the "User tagged samples" tables. Unfortunately we have two separate tables in DB for "existing" and "user tagged" samples, maybe it would be possible to somehow merge them and have only one.

In principle, we can just drop the user_tags and keep the existing_campaigns table selecting on tag as the query for the user_tag page or join two queries from the two separate tables of user_tag entries and existing_campaigns? What do you think?
I think I covered the rest of the issues!

2021-11-29 13:08 UTC, justinasr commented on update_scripts/update_user_samples.py
> +        campaign_names = [v.split('*')[0] for d in campaign_names for k, v in d.items()]
Hm, this makes an assumption that all campaigns (GEN, Mini, Nano) have identical substrings in the front. While it is true based on the PdmV policy, it's a risky assumption to take.

2021-11-29 13:25 UTC, justinasr commented on update_scripts/update_user_samples.py
> +    def get_table_names_(self):
Well, `get_table_names` is used in multiple places, including `get_existing_sample` and `insert_or_update` methods. If we are changing the whole structure so there would be only one table, then this method becomes irrelevant and probably only the `update` method should be overwritten. Maybe not even the whole method, but just the `requests = self.mcm.get('requests', 'tags=%s' % (tag_name))` part - essentially now the only thing that is different between existing samples and user samples is query done to McM to fetch relevant requests.

2021-11-29 13:25 UTC, justinasr commented on update_scripts/update_user_samples.py
> +    def get_table_names_(self):
Well, `get_table_names` is used in multiple places, including `get_existing_sample` and `insert_or_update` methods. If we are changing the whole structure so there would be only one table, then this method becomes irrelevant and probably only the `update` method should be overwritten. Maybe not even the whole method, but just the `requests = self.mcm.get('requests', 'tags=%s' % (tag_name))` part - essentially now the only thing that is different between existing samples and user samples is query done to McM to fetch relevant requests.

2021-11-30 10:50 UTC, merged